modLoader="javafml" #mandatory
loaderVersion="[40,)"
license="MIT"
[[mods]]
    modId="moremountedstorages" #mandatory
    version="${file.jarVersion}" #mandatory
    displayName="More Mounted Storages" #mandatory
    logoFile="logo.png" #optional
    issueTrackerURL="https://github.com/juh9870/MoreMountedStorages/issues" #optional
    authors="juh9870" #optional
    description='''Allows storages from various mods to be used as a part of Create moving contraptions.
Suppoted mods:
    - Ender Storage https://www.curseforge.com/minecraft/mc-mods/ender-storage-1-8
    - Iron Chests https://www.curseforge.com/minecraft/mc-mods/iron-chests
    - Storage Drawers https://www.curseforge.com/minecraft/mc-mods/storage-drawers
    - Framed Compacting Drawers https://www.curseforge.com/minecraft/mc-mods/framed-compacting-drawers
    - Immersive Engineering https://www.curseforge.com/minecraft/mc-mods/immersive-engineering
    - Industrial Foregoing https://www.curseforge.com/minecraft/mc-mods/industrial-foregoing
    - PneumaticCraft: Repressurized https://www.curseforge.com/minecraft/mc-mods/pneumaticcraft-repressurized
    - Expanded Storage: https://www.curseforge.com/minecraft/mc-mods/expanded-storage-forge
    - DimStorage: https://www.curseforge.com/minecraft/mc-mods/dimstorage
    # - Storage Overhaul: https://www.curseforge.com/minecraft/mc-mods/storage-overhaul'''
[[dependencies.moremountedstorages]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[40,)" #mandatory
    ordering="NONE"
    side="BOTH"
# Here's another dependency
[[dependencies.moremountedstorages]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.moremountedstorages]]
    modId="create"
    mandatory=true
    versionRange="[0.5.0c,)" #keep updated
    ordering="NONE"
    side="BOTH"
[[dependencies.moremountedstorages]]
    modId="enderstorage"
    mandatory=false
    versionRange="[2.9.0.177,)" #keep updated
    ordering="AFTER"
    side="BOTH"
[[dependencies.moremountedstorages]]
    modId="storagedrawers"
    mandatory=false
    versionRange="[10.2,)" #keep updated
    ordering="AFTER"
    side="BOTH"
[[dependencies.moremountedstorages]]
    modId="framedcompactdrawers"
    mandatory=false
    versionRange="[1.18-4.1.0,)" #keep updated
    ordering="AFTER"
    side="BOTH"
[[dependencies.moremountedstorages]]
    modId="immersiveengineering"
    mandatory=false
    versionRange="[1.18.2-8.0.2-149,)" #keep updated
    ordering="AFTER"
    side="BOTH"
[[dependencies.moremountedstorages]]
    modId="industrialforegoing"
    mandatory=false
    versionRange="[3.3.1.4,)" #keep updated
    ordering="AFTER"
    side="BOTH"
[[dependencies.moremountedstorages]]
    modId="pneumaticcraft"
    mandatory=false
    versionRange="[1.18.2-3.3.1-110,)" #keep updated
    ordering="AFTER"
    side="BOTH"
[[dependencies.moremountedstorages]]
    modId="expandedstorage"
    mandatory=false
    versionRange="[7.4.0-beta.4,)" #keep updated
    ordering="AFTER"
    side="BOTH"
[[dependencies.moremountedstorages]]
    modId="trashcans"
    mandatory=false
    versionRange="[1.0.15,)" #keep updated
    ordering="AFTER"
    side="BOTH"
[[dependencies.moremountedstorages]]
    modId="enderchests"
    mandatory=false
    versionRange="[1.9.5,)" #keep updated
    ordering="AFTER"
    side="BOTH"
#[[dependencies.moremountedstorages]]
#    modId="storage_overhaul"
#    mandatory=false
#    versionRange="[1.0.4,)" #keep updated
#    ordering="AFTER"
#    side="BOTH"